
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from tkinter import filedialog
import BaiGUI_AI
from PIL import Image
from PIL import ImageTk
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\build\assets\frame0")

url = "C:/TRITUENHANTAO/Baicuoiki/Test_animals-20230516T042741Z-001/Test_animals/cat.jpg"

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
_ = Image.open("C:\\TRITUENHANTAO\\Baicuoiki\\assets\\frame0\\image_1.png")
_ = ImageTk.PhotoImage(_)
window.geometry("500x350")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 350,
    width = 500,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

def openFile():
    filepath = filedialog.askopenfilename(initialdir="C:\\TRITUENHANTAO\\Baicuoiki\\Test_animals-20230516T042741Z-001\\Test_animals",title="Open file Okey?",filetypes=(("Image file","*.png"), ("Image file","*.jpg"),("all file","*.*")))
    print(filepath)
    global url
    url = filepath
    global _
    _ = Image.open(filepath)
    _ = _.resize((250, 250))
    _ = ImageTk.PhotoImage(_)

    canvas.itemconfig(image_1, image=_)



button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=openFile,
    relief="flat"
)
button_1.place(
    x=313.0,
    y=76.0,
    width=150.0,
    height=30.0
)
def predict():
    result = BaiGUI_AI.predict(url)
    canvas.itemconfig(resultText, text=result)


image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    152.0,
    201.0,
    image=_
)
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=predict,
    relief="flat"
)
button_2.place(
    x=313.0,
    y=130.0,
    width=150.0,
    height=30.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    388.0,
    255.0,
    image=image_image_2
)
resultText = canvas.create_text(
    390.0,
    260.0,
    anchor="center",
    text="ABCD",
    justify="center",
    fill="#000000",
    font=("IstokWeb Bold", 35 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    388.0,
    201.0,
    image=image_image_3
)

canvas.create_text(
    69.0,
    18.0,
    anchor="nw",
    text="DỰ ĐOÁN ĐỘNG VẬT ",
    fill="#FF3C3C",
    font=("IstokWeb Bold", 35 * -1)
)
window.resizable(False, False)
window.mainloop()
